# Generated by Django 3.2.5 on 2024-07-31 00:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uranel_django_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initule_depense', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'depens',
                'verbose_name_plural': 'depenses',
            },
        ),
        migrations.CreateModel(
            name='Sexe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_sexe', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Sexe',
                'verbose_name_plural': 'Sexes',
            },
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={},
        ),
        migrations.RenameField(
            model_name='client',
            old_name='civilite',
            new_name='adresse',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='numero_clien',
            new_name='numero_client',
        ),
        migrations.RenameField(
            model_name='consultation',
            old_name='observation',
            new_name='diagnostique',
        ),
        migrations.RenameField(
            model_name='consultation',
            old_name='ordonnance',
            new_name='plainte',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='dates_stock',
            new_name='dates_entree',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='prix_convenu',
            new_name='quantite',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='type_operation',
            new_name='type_operationn',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='remise',
        ),
        migrations.AddField(
            model_name='article',
            name='prix',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='age',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consultation',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='uranel_django_app.client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consultation',
            name='traitement',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paiement',
            name='facture',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='libelle_article',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='libelle_categorie',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dates_stock', models.DateField(auto_now_add=True)),
                ('numero_facture', models.CharField(max_length=50)),
                ('quantite', models.FloatField()),
                ('montant_fixe', models.FloatField()),
                ('prix_convenu', models.FloatField()),
                ('remise', models.FloatField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uranel_django_app.article')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uranel_django_app.client')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('type_operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uranel_django_app.type_operation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vente',
                'verbose_name_plural': 'ventes',
            },
        ),
        migrations.CreateModel(
            name='Sortie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dates_sortie', models.DateField(auto_now_add=True)),
                ('montant_depense', models.FloatField()),
                ('depense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uranel_django_app.depense')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sortie',
                'verbose_name_plural': 'Sorties',
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dates_prescription', models.DateField(auto_now_add=True)),
                ('Prescription', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uranel_django_app.client')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prescription',
                'verbose_name_plural': 'Prescriptions',
            },
        ),
        migrations.CreateModel(
            name='Ordonnance_lunette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dates_ordonnance', models.DateField(auto_now_add=True)),
                ('sphere_vl_od', models.CharField(default='(vide)', max_length=30)),
                ('cylindre_vl_od', models.CharField(default='(vide)', max_length=30)),
                ('axe_vl_od', models.CharField(default='(vide)', max_length=30)),
                ('addition_vl_od', models.CharField(default='(vide)', max_length=30)),
                ('sphere_vp_od', models.CharField(default='(vide)', max_length=30)),
                ('cylindre_vp_od', models.CharField(default='(vide)', max_length=30)),
                ('axe_vp_od', models.CharField(default='(vide)', max_length=30)),
                ('addition_vp_od', models.CharField(default='(vide)', max_length=30)),
                ('sphere_vl_og', models.CharField(default='(vide)', max_length=30)),
                ('cylindre_vl_og', models.CharField(default='(vide)', max_length=30)),
                ('axe_vl_og', models.CharField(default='(vide)', max_length=30)),
                ('addition_vl_og', models.CharField(default='(vide)', max_length=30)),
                ('sphere_vp_og', models.CharField(default='(vide)', max_length=30)),
                ('cylindre_vp_og', models.CharField(default='(vide)', max_length=30)),
                ('axe_vp_og', models.CharField(default='(vide)', max_length=30)),
                ('addition_vp_og', models.CharField(default='(vide)', max_length=30)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uranel_django_app.client')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ordonnance_lunette',
                'verbose_name_plural': 'Ordonnance_lunettes',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='sexe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='uranel_django_app.sexe'),
            preserve_default=False,
        ),
    ]
