# Generated by Django 4.2.14 on 2024-08-01 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uranel_django_app', '0002_auto_20240731_0124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entree_stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dates_entree', models.DateField(auto_now_add=True)),
                ('quantite', models.FloatField()),
                ('montant_fixe', models.FloatField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uranel_django_app.article')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sortie_stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dates_entree', models.DateField(auto_now_add=True)),
                ('facture', models.CharField(max_length=30)),
                ('quantite', models.FloatField()),
                ('montant_fixe', models.FloatField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uranel_django_app.article')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uranel_django_app.client')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
