# Generated by Django 4.2.14 on 2024-08-03 15:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('uranel_django_app', '0003_entree_stock_sortie_stock_delete_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='dates_client',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
