# Generated by Django 4.2.14 on 2024-08-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uranel_django_app', '0004_client_dates_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='dates_client',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
