# Generated by Django 4.2.14 on 2024-08-04 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uranel_django_app', '0006_client_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entree_stock',
            old_name='montant_fixe',
            new_name='montant',
        ),
        migrations.RenameField(
            model_name='sortie_stock',
            old_name='dates_entree',
            new_name='dates_sortie',
        ),
        migrations.RenameField(
            model_name='sortie_stock',
            old_name='montant_fixe',
            new_name='montant',
        ),
    ]
