# Generated by Django 4.2.14 on 2024-08-05 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uranel_django_app', '0007_rename_montant_fixe_entree_stock_montant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='type_verre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_type_verre', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Type_verre',
                'verbose_name_plural': 'Type_verres',
            },
        ),
    ]
