# Generated by Django 4.2.14 on 2024-08-05 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uranel_django_app', '0008_type_verre'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordonnance_lunette',
            name='type_verre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='uranel_django_app.type_verre'),
            preserve_default=False,
        ),
    ]
