# Generated by Django 4.2.14 on 2024-08-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uranel_django_app', '0009_ordonnance_lunette_type_verre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='adresse',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='client',
            name='nom_client',
            field=models.CharField(max_length=120),
        ),
    ]
