# Generated by Django 4.2.14 on 2024-08-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uranel_django_app', '0011_historicalvente_historicalsortie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_telephone1', models.CharField(max_length=30)),
                ('numero_telephone2', models.CharField(max_length=30)),
                ('mail1', models.CharField(max_length=30)),
                ('mail2', models.CharField(max_length=30)),
                ('adresse', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'informations',
                'verbose_name_plural': 'information',
            },
        ),
    ]
