# Generated by Django 4.2.14 on 2024-08-16 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uranel_django_app', '0012_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='adresse',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='information',
            name='mail1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='information',
            name='mail2',
            field=models.CharField(max_length=50),
        ),
    ]
