# Generated by Django 4.2.14 on 2024-08-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uranel_django_app', '0013_alter_information_adresse_alter_information_mail1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvente',
            name='total',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vente',
            name='total',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
