# Generated by Django 4.2.14 on 2024-08-25 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uranel_django_app', '0015_matierepremierelunette_pointfocallunette_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='stock_lunette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dates', models.DateField(auto_now_add=True)),
                ('quantites', models.FloatField()),
                ('prix_unitaire', models.FloatField()),
                ('Lunette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uranel_django_app.lunette')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('type_operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uranel_django_app.type_operation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'stock_lunettes',
                'verbose_name_plural': 'stock_lunette',
            },
        ),
    ]
