# Generated by Django 4.2.14 on 2024-08-27 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uranel_django_app', '0018_alter_historicalordonnance_lunette_type_verre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sortie_stock',
            name='article',
        ),
        migrations.RemoveField(
            model_name='sortie_stock',
            name='client',
        ),
        migrations.RemoveField(
            model_name='sortie_stock',
            name='site',
        ),
        migrations.RemoveField(
            model_name='sortie_stock',
            name='user',
        ),
        migrations.DeleteModel(
            name='Entree_stock',
        ),
        migrations.DeleteModel(
            name='Sortie_stock',
        ),
    ]
