# Generated by Django 4.2.14 on 2024-08-27 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('uranel_django_app', '0019_remove_sortie_stock_article_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='stock_autre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dates_entree', models.DateField(auto_now_add=True)),
                ('quantite', models.FloatField()),
                ('montant', models.FloatField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uranel_django_app.article')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('type_operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uranel_django_app.type_operation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
