# Generated by Django 4.2.14 on 2024-08-27 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uranel_django_app', '0020_stock_autre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalvente',
            name='type_operation',
        ),
        migrations.RemoveField(
            model_name='vente',
            name='type_operation',
        ),
    ]
