# Generated by Django 4.2.14 on 2024-08-29 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uranel_django_app', '0022_stock_autre_prix_unitaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock_autre',
            name='montant',
        ),
    ]
