# Generated by Django 4.2.14 on 2024-08-30 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uranel_django_app', '0023_remove_stock_autre_montant'),
    ]

    operations = [
        migrations.AddField(
            model_name='lunette',
            name='prix_article',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
