# Generated by Django 4.2.14 on 2024-09-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uranel_django_app', '0024_lunette_prix_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_lunette',
            name='motif',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
