# Generated by Django 4.2.14 on 2024-09-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uranel_django_app', '0025_stock_lunette_motif'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_autre',
            name='motif',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
