# Generated by Django 4.2.14 on 2024-09-25 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('uranel_django_app', '0026_stock_autre_motif'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalStock',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('dates_stock', models.DateField(blank=True, editable=False)),
                ('numero_facture', models.CharField(max_length=50)),
                ('quantite', models.FloatField()),
                ('montant_fixe', models.FloatField()),
                ('prix_convenu', models.FloatField()),
                ('remise', models.FloatField()),
                ('total', models.FloatField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('Type_operation', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uranel_django_app.type_operation')),
                ('article', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uranel_django_app.article')),
                ('client', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uranel_django_app.client')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='auth.group')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Vente',
                'verbose_name_plural': 'historical ventes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dates_stock', models.DateField(auto_now_add=True)),
                ('numero_facture', models.CharField(max_length=50)),
                ('quantite', models.FloatField()),
                ('montant_fixe', models.FloatField()),
                ('prix_convenu', models.FloatField()),
                ('remise', models.FloatField()),
                ('total', models.FloatField()),
                ('Type_operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uranel_django_app.type_operation')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uranel_django_app.article')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uranel_django_app.client')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vente',
                'verbose_name_plural': 'ventes',
            },
        ),
        migrations.RemoveField(
            model_name='vente',
            name='article',
        ),
        migrations.RemoveField(
            model_name='vente',
            name='client',
        ),
        migrations.RemoveField(
            model_name='vente',
            name='site',
        ),
        migrations.RemoveField(
            model_name='vente',
            name='user',
        ),
        migrations.DeleteModel(
            name='HistoricalVente',
        ),
        migrations.DeleteModel(
            name='Vente',
        ),
    ]
