# Generated by Django 4.2.14 on 2024-09-25 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uranel_django_app', '0027_historicalstock_stock_remove_vente_article_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uranel_django_app.client'),
        ),
    ]
