# Generated by Django 4.2.14 on 2024-09-30 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uranel_django_app', '0028_alter_stock_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='libelle_article',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='libelle_article',
            field=models.CharField(max_length=150),
        ),
    ]
